# In: navigation_stack/configs/mppi_config.yaml

# Configuration for the PyTorch-based MPPI Controller

simulation:
  num_samples: 1500     # (K) Number of trajectories to sample
  horizon_steps: 50       # (T) Number of timesteps in the horizon
  dt: 0.1             # Timestep (seconds)
  lambda_: 1.5            # Temperature parameter for weighting

robot_limits:
  max_linear_vel: 0.28     # m/s
  max_angular_vel: 0.23   # rad/s (approx. pi)
  safety_radius: 0.5     # (meters) The robot's "safety bubble" for obstacles

noise_params:
  v_std: 0.07             # Linear velocity noise std dev
  omega_std: 0.07          # Angular velocity noise std dev

cost_weights:
  tracking: 100.0          # (w_track) Penalizes straying from the global path
  obstacle: 80.0         # (w_obs) Penalizes getting close to Lidar points (set high!)
  goal: 100.0              # (w_goal) Rewards making progress toward the target waypoint
  control_cost: 0.5     # (w_control) Penalizes high-effort motor commands
  smoothing: 4.0        # (w_smooth) Penalizes jerky movements
  
  
grid_params:
  resolution: 0.05
  width_m: 30.0
  height_m: 30.0
